#!/usr/bin/env bash
# Script that displays information about domain and it's subdomains

function domain_zone() {
	domain="$1"
    	subdomain="$2"
    	subdomains=("www" "lb-01" "web-01" "web-02")
	record_type=("A" "CNAME")

	# if specific subdomain provided, display information for that subdomain

    	if [[ -n "$subdomain" ]]
    	then
		subdomains=("$subdomain")
	fi

    	for sub in "${subdomains[@]}"; do
		for type in "${record_type[@]}"; do
			# awk is used to extract IP address or hostname from DNS response
			destination=$(dig +short "$sub.$domain" "$type" | awk '{ print $NF }')
			if [[ -n "$destination" ]]; then
				echo "The subdomain $sub is a $type record and points to $destination"
				break
			fi
		done
	done
}

if [[ $# -lt 1 ]]; then
	echo "Usage: $0 <domain> [<subdomain>]"
	exit 1
fi

domain_zone "$1" "$2"
