#!/usr/bin/env bash
# Script that installs and configures nginx in new ubuntu machine.

# Install NGINX server
sudo apt-get -y update
sudo apt-get -y install nginx

# Start NGINX service
sudo service nginx start

# Reconfigure firewall
sudo ufw allow 'Nginx HTTP'

# grant user ownership and permission
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Back up the default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# create new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

#setting up redirection
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
