#!/usr/bin/env bash
# Connects to server with key in ~/.ssh/school
# web-01 server
#ssh -i ~/.ssh/id_rsa ubuntu@3.85.41.105

# web-02 server
ssh -i ~/.ssh/id_rsa ubuntu@54.237.92.166

# Load balancer
#ssh -i ~/.ssh/id_rsa ubuntu@100.25.117.140




#copying public key to remote hosts.
#ssh-copy-id -i /root/.ssh/id_rsa.pub ubuntu@100.26.254.98

